CREATE TABLE IF NOT EXISTS projects(
  id integer primary key generated by default as IDENTITY,
  name VARCHAR (50) not null,
  description text,
  delivery_date date not null
);

CREATE TABLE IF NOT EXITST tasks (
  id integer primary key generated by default as IDENTITY,
  name varchar (50) not null,
  done BOOLEAN,
  project_id integer references projects(id)
);
